// Barrel — re-exports from widget-types.ts and widget-fields.ts
export type {
  ActivityPill,
  ActivityBarConfig,
  CameraEntry,
  CameraStreamMode,
  CameraCardConfig,
  WeatherCardConfig,
  EnergyCardConfig,
  TempoCardConfig,
  ThermostatCardConfig,
  RoomControl,
  RoomEntry,
  RoomsGridConfig,
  ShortcutEntry,
  ShortcutsCardConfig,
  GreetingCardConfig,
  SensorVariant,
  SensorCardConfig,
  LightCardConfig,
  PersonEntry,
  PersonStatusConfig,
  CoverCardConfig,
  TemplateCardConfig,
  AutomationCardConfig,
  MediaPlayerCardConfig,
  AlarmCardConfig,
  VacuumRoom,
  VacuumSelectEntity,
  VacuumCardConfig,
  PelletCardConfig,
  WidgetConfig,
  WidgetConfigs,
} from './widget-types';

export { DEFAULT_WIDGET_CONFIGS, WIDGET_FIELD_DEFS } from './widget-fields';
export type { WidgetFieldDef } from './widget-fields';
