// Barrel — re-exports from widget-types.ts and widget-fields.ts
export type {
  ActivityPill,
  ActivityBarConfig,
  CameraEntry,
  CameraStreamMode,
  CameraCardConfig,
  WeatherCardConfig,
  EnergyCardConfig,
  EnergyFlowCardConfig,
  TempoCardConfig,
  ThermostatCardConfig,
  RoomControl,
  RoomEntry,
  RoomsGridConfig,
  RoomCardConfig,
  GroupChild,
  GroupCardConfig,
  ButtonCardConfig,
  ShortcutEntry,
  ShortcutsCardConfig,
  GreetingCardConfig,
  SensorVariant,
  SensorCardConfig,
  LightCardConfig,
  PersonEntry,
  PersonStatusConfig,
  CoverCardConfig,
  TemplateCardConfig,
  AutomationCardConfig,
  AutomationItem,
  AutomationListCardConfig,
  MediaPlayerCardConfig,
  AlarmCardConfig,
  VacuumRoom,
  VacuumSelectEntity,
  VacuumCardConfig,
  PelletCardConfig,
  ChartVariant,
  ChartCardConfig,
  BatteriesCardConfig,
  LockCardConfig,
  CalendarCardConfig,
  TodoCardConfig,
  FanCardConfig,
  ClockCardConfig,
  WidgetConfig,
  WidgetConfigs,
} from './widget-types';

export type { WidgetFieldDef } from './widget-fields';

// `DEFAULT_WIDGET_CONFIGS` / `WIDGET_FIELD_DEFS` ne se réexportent plus d'ici :
// ces registres sont désormais dérivés des manifestes de widgets. Les importer
// depuis `@/widgets`, seule source qui tienne compte de `defineWidget`.
